name: Create AMI and Deploy EC2 Instance

on:
  push:
    branches:
      - main  # Adjust the branch as necessary

jobs:
  create-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Adjust the region as necessary

      - name: Create AMI from EC2 instance
        id: create_ami
        run: |
          INSTANCE_ID="i-02dc95e2d59cf05b4"  # Replace with your instance ID
          AMI_NAME="my-ami-$(date +%Y-%m-%d-%H-%M-%S)"
          # Create an AMI from the specified EC2 instance
          AMI_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name $AMI_NAME --no-reboot --query 'ImageId' --output text)
          echo "AMI creation initiated with ID $AMI_ID"

      - name: Wait for the AMI to be available
        id: wait_for_ami
        run: |
          AMI_NAME="my-ami-$(date +%Y-%m-%d-%H-%M-%S)"
          echo "Checking for AMI with name $AMI_NAME"
          AMI_ID=$AMI_ID
          # Loop until the AMI is available
          while true; do
            AMI_STATE=$(aws ec2 describe-images --image-ids $AMI_ID --query 'Images[0].State' --output text)
            if [ "$AMI_STATE" = "available" ]; then
              echo "AMI $AMI_ID is available"
              break
            else
              echo "AMI $AMI_ID is not yet available, waiting..."
              sleep 10  # Wait for 10 seconds before checking again
            fi
          done
