name: Create AMI.

on:
  push:
    branches:
      - main  # Adjust the branch as necessary

jobs:
  create-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Adjust the region as necessary

      - name: Create AMI from EC2 instance
        id: create_ami
        run: |
          INSTANCE_ID="i-02dc95e2d59cf05b4"  # Replace with your instance ID
          AMI_NAME="my-ami-$(date +%Y-%m-%d-%H-%M-%S)"
          aws ec2 create-image --instance-id $INSTANCE_ID --name $AMI_NAME --no-reboot

      - name: Get AMI ID
        id: ami_id
        run: |
          echo "AMI_ID=$(aws ec2 describe-images --owners self --filters "Name=name,Values=$AMI_NAME" --query "Images[0].ImageId" --output text)" >> $GITHUB_ENV

      - name: Print AMI ID
        run: echo "Created AMI with ID ${{ env.AMI_ID }}"
